### ISSUE TITLE
help please!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [javedali99/audio-to-text-transcription#1]
C:\Users\User\Downloads\audio-to-text-transcription-main\audio-to-text-transcription-main>python youtube_audio_to_text.py
Enter the YouTube video URL: https://www.youtube.com/watch?v=r9h-0lDrTdA&t=5s
Audio downloaded to YoutubeAudios/audio.mp3
C:\Users\User\AppData\Roaming\Python\Python311\site-packages\whisper\transcribe.py:114: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

**Comment by javedali99** [comment]
@KENPOKASMMA1982 The message you're seeing is a warning, not an error. It originates from the `whisper` module the script uses for transcription. The warning indicates that the module attempted to use 16-bit Floating Point (FP16) precision, which is often optimized for certain GPUs. However, since it's running on a CPU that doesn't support FP16, it defaults to 32-bit Floating Point (FP32) precision instead. This might result in slightly slower performance, but the script should continue to function without issues.

**Comment by KENPOKASMMA1982** [comment]
hello my friend!!!could you tell me step ,by step what I have to do to use our amazing project?

**Comment by javedali99** [comment]
@KENPOKASMMA1982 Check this blog post for the instructions: https://www.javedali.net/post/2023-04-audio-to-text/
